---
title: "TOS2020 chapter 3.5: final combinations"
output: html_notebook
---

```{r}
library(tidyverse)
library(plyr)
library(psych)
library(ggplot2)
library(lm.beta)
library(lme4)
library(emmeans)
```

```{r}
load("~/Google Drive/ABCD/ABCD_puberty/_data/TOS2020/TOS2020_chp3.RData")
load("~/Google Drive/ABCD/ABCD_puberty/_data/TOS2020/TOS2020_chp2_1.RData")
```

```{r}
#data_all<-data_all[data_all$PCScore != "mid_x", ] # removing mid_x, as they don't appear to fit into the predefined groups
#data_all<-data_all[!is.na(data_all$subjectkey), ]
# d<-df[!is.na(df$PCScore), ]

data_all$gender<-as.factor(data_all$gender)
levels(as.factor(data_all$RaceEth))
data_all$RaceEth <- factor(data_all$RaceEth, levels = c("white", 
                                  "white and Hispanic",
                                  "Asian Indian", 
                                  "Asian Indian and Hispanic", 
                                  "Black/African American", 
                                  "Black/African American and Hispanic",
                                  "Chinese", 
                                  "Filipino", 
                                  "Filipino and Hispanic", 
                                  "Japanese", 
                                  "Korean", 
                                  "Korean and Hispanic", 
                                  "Samoan", 
                                  "Vietnamese",
                                  "Other Asian", 
                                  "Other Asian and Hispanic", 
                                  "Native American", 
                                  "Native American and Hispanic", 
                                  "Other pacific islander", 
                                  "Other Race", 
                                  "Other Race and Hispanic", 
                                  "Refused answer and Hispanic",
                                  "Don't know and Hispanic"
                                 ))

summary(data_all$RaceEth)
levels(as.factor(data_all$SES))
levels(as.factor(data_all$gender))
data_all$gender<-factor(data_all$gender, levels = c("M","F"))
summary(data_all$gender)

levels(as.factor(data_all$PCScore))
data_all$PCScore<-factor(data_all$PCScore, levels = c ("early", "mid", "late", "post"))
summary(data_all$PCScore)

levels(as.factor(data_all$ovob))
data_all$ovob<-factor(data_all$ovob, levels = c("average", "low", "overweight", "obese"))

levels(as.factor(data_all$central_ob))
```

```{r}
scanner_type<-df_subcort %>%
  select(subjectkey, scanner_type_pd)
  
subcort<-df_subcort %>%
  select(subjectkey, contains("caudate"),contains("putamen"),contains("pallidum"), contains("thlpp"),contains("amygdala"), contains("accarea"), contains("ventraldc"), contains("hthp"), scanner_type_pd)
# head(subcort)

# data_all$WCsds

base<-data_all %>%
  select(subjectkey, subjectkey, interview_age, gender, anthroheightcalc, anthroweightcalc, anthro_waist_cm, PCSum, RaceEth, SES, age_years, PCScore, gender, hormone_scr_hse_mean, hormone_scr_dhea_mean, hormone_scr_ert_mean, BMIsds, BMIper, central_ob, ovob, WCsds, fmri_beta_gparc_mean_motion)

df<- merge(base, subcort)
```

#### Caudate
Aim 2
##### Anticipation
```{r}
AntciCaudate<- df %>%
  select(subjectkey, contains("mdacrwvsnt")) %>%
  select(subjectkey, contains("caudate"))

AnticCaudateL_summary<-AntciCaudate %>%
  select(subjectkey, mdacrwvsntblcaudate)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

AnticCaudateR_summary<-AntciCaudate %>%
  select(subjectkey, mdacrwvsntbrightcaudate)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

AntCaudate<-merge(AnticCaudateL_summary, AnticCaudateR_summary)
head(AntCaudate)
colnames(AntCaudate)<-c("subjectkey","ant_caudate_L","ant_caudate_R")
```
##### Reward
```{r}
RewCaudate<- df %>%
  select(subjectkey, contains("midrwpvnfkb")) %>%
  select(subjectkey, contains("caudate"))
head(RewCaudate)

RewCaudateR_summary<-RewCaudate %>%
  select(subjectkey, midrwpvnfkbrightcaudate)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

RewCaudateL_summary<-RewCaudate %>%
  select(subjectkey, midrwpvnfkblcaudate)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

RewCaudate<-merge(RewCaudateL_summary, RewCaudateR_summary)
head(RewCaudate)
colnames(RewCaudate)<-c("subjectkey","Rew_caudate_L","Rew_caudate_R")
```

##### Loss
```{r}
LossCaudate<- df %>%
  select(subjectkey, contains("midlspvnfkb")) %>%
  select(subjectkey, contains("caudate"))
head(LossCaudate)

LossCaudateR_summary<-LossCaudate %>%
  select(subjectkey, midlspvnfkbrightcaudate)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

LossCaudateL_summary<-LossCaudate %>%
  select(subjectkey, midlspvnfkblcaudate)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

LossCaudate<-merge(LossCaudateL_summary, LossCaudateR_summary)
dim(LossCaudate)
colnames(LossCaudate)<-c("subjectkey","Loss_caudate_L","Loss_caudate_R")
```
##### Merge
```{r}
Caudate1<-merge(AntCaudate, RewCaudate)
Caudate<-merge(Caudate1, LossCaudate)
```


#### Putamen
Aim 2
##### Anticipation
```{r}
AntciPutamen<- df %>%
  select(subjectkey, contains("mdacrwvsnt")) %>%
  select(subjectkey, contains("putamen"))

AnticPutamenL_summary<-AntciPutamen %>%
  select(subjectkey, mdacrwvsntblputamen)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

AnticPutamenR_summary<-AntciPutamen %>%
  select(subjectkey, mdacrwvsntbrightputamen)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

AntPutamen<-merge(AnticPutamenL_summary, AnticPutamenR_summary)
head(AntPutamen)
colnames(AntPutamen)<-c("subjectkey","ant_putamen_L","ant_putamen_R")
```
##### Reward
```{r}
RewPutamen<- df %>%
  select(subjectkey, contains("midrwpvnfkb")) %>%
  select(subjectkey, contains("putamen"))
head(RewPutamen)

RewPutamenR_summary<-RewPutamen %>%
  select(subjectkey, midrwpvnfkbrightputamen)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

RewPutamenL_summary<-RewPutamen %>%
  select(subjectkey, midrwpvnfkblputamen)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

RewPutamen<-merge(RewPutamenL_summary, RewPutamenR_summary)
head(RewPutamen)
colnames(RewPutamen)<-c("subjectkey","Rew_putamen_L","Rew_putamen_R")
```

##### Loss
```{r}
LossPutamen<- df %>%
  select(subjectkey, contains("midlspvnfkb")) %>%
  select(subjectkey, contains("putamen"))
head(LossPutamen)

LossPutamenR_summary<-LossPutamen %>%
  select(subjectkey, midlspvnfkbrightputamen)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

LossPutamenL_summary<-LossPutamen %>%
  select(subjectkey, midlspvnfkblputamen)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))

LossPutamen<-merge(LossPutamenL_summary, LossPutamenR_summary)
head(LossPutamen)
colnames(LossPutamen)<-c("subjectkey","Loss_putamen_L","Loss_putamen_R")
```
##### Merge
```{r}
Putamen1<-merge(AntPutamen, RewPutamen)
Putamen<-merge(Putamen1, LossPutamen)
head(Putamen)
```

```{r}
Putamen$PutamenAntVsRewL<- Putamen$ant_putamen_L - Putamen$Rew_putamen_L
Putamen$PutamenAntVsRewR<-  Putamen$ant_putamen_R - Putamen$Rew_putamen_R

Putamen$PutamenRewVsLossL<- Putamen$Rew_putamen_L - Putamen$Loss_putamen_L
Putamen$PutamenRewVsLossR<-  Putamen$Rew_putamen_R - Putamen$Loss_putamen_R

head(Putamen)

Caudate$CaudateAntVsRewL<- Caudate$ant_caudate_L - Caudate$Rew_caudate_L
Caudate$CaudateAntVsRewR<-  Caudate$ant_caudate_R - Caudate$Rew_caudate_R

Caudate$CaudateRewVsLossL<- Caudate$Rew_caudate_L - Caudate$Loss_caudate_L
Caudate$CaudateRewVsLossR<-  Caudate$Rew_caudate_R - Caudate$Loss_caudate_R
  
head(Caudate)

inter<-merge(Putamen, Caudate)
head(inter)
subcort_RwLsAn<-merge(inter, base)
dim(subcort_RwLsAn)

```

### Posterior cingulate
* midrwpvnfkbctxlhbankssts ==> reward 
* midlspvnfkbrightventraldc ==> loss

```{r}
# PC posterior cingulate 
RewPCLh<- data_all %>%
  select(subjectkey, midrwposvsnegfkbetactxlhgp12,midrwposvsnegfkbetactxlhgp13, midrwposvsnegfkbetactxlhgp14, midrwposvsnegfkbetactxlhgp20, midrwposvsnegfkbetactxlhgp89, midrwposvsnegfkbetactxlhgp93, midrwposvsnegfkbetactxlhgp150) 

fcols<-c("midrwposvsnegfkbetactxlhgp12","midrwposvsnegfkbetactxlhgp13","midrwposvsnegfkbetactxlhgp14", "midrwposvsnegfkbetactxlhgp20", "midrwposvsnegfkbetactxlhgp89", "midrwposvsnegfkbetactxlhgp93", "midrwposvsnegfkbetactxlhgp150")

RewPCLh$Reward_meanPClh <- rowMeans(RewPCLh[fcols], na.rm=TRUE)
```

```{r}
RewPCRh<- data_all %>%
  select(subjectkey, contains("midrwposvsnegfkbetactxrh"))%>%
  select(subjectkey, contains("hgp162"), contains("hgp162"), contains("hgp173"), contains("hgp174"), contains("hgp176"), contains("hgp180"), contains("hgp186"), contains("hgp254"))
dim(RewPCRh)

RewPCRh$Reward_meanPCrh <- rowMeans(RewPCRh[,2:8], na.rm=TRUE)
```

```{r}
LossPCLh<- data_all %>%
  select(subjectkey, midlossposvsnegfkbctxlhgp12, midlossposvsnegfkbctxlhgp13, midlossposvsnegfkbctxlhgp14, midlossposvsnegfkbctxlhgp20, midlossposvsnegfkbctxlhgp89, midlossposvsnegfkbctxlhgp93, midlossposvsnegfkbctxlhgp150)
dim(LossPCLh)
LossPCLh$Loss_meanPClh <- rowMeans(LossPCLh[,2:8], na.rm=TRUE)
colnames(LossPCLh)
```

```{r}
LossPCRh<- data_all %>%
  select(subjectkey, contains("midlossposvsnegfkbctxrh"))%>%
  select(subjectkey, contains("hgp162"), contains("hgp162"), contains("hgp173"), contains("hgp174"), contains("hgp176"), contains("hgp180"), contains("hgp186"), contains("hgp254"))
dim(LossPCRh)

LossPCRh$Loss_meanPCrh <- rowMeans(LossPCRh[,2:8], na.rm=TRUE)
```

```{r}
head(LossPCLh)
LossPCLh_summary<-LossPCLh %>%
  select(subjectkey, Loss_meanPClh)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))
dim(LossPCLh_summary)
```
```{r}
head(LossPCRh)
LossPCRh_summary<-LossPCRh %>%
  select(subjectkey, Loss_meanPCrh)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))
head(LossPCRh_summary)
```

```{r}
colnames(RewPCLh)
RewPCLh_summary<-RewPCLh %>%
  select(subjectkey, Reward_meanPClh)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))
head(RewPCLh_summary)
```

```{r}
head(RewPCRh)
RewPCRh_summary<-RewPCRh %>%
  select(subjectkey, Reward_meanPCrh)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))
head(RewPCRh_summary)
```

```{r}
summary(LossPCLh$subjectkey)
PC_L<-merge(LossPCLh_summary, RewPCLh_summary)
dim(PC_L)
PC_R<-merge(LossPCRh_summary, RewPCRh_summary)
PC<-merge(PC_L, PC_R)
head(PC)
PC$RewVLoss_PC_L<- PC$Reward_meanPClh - PC$Loss_meanPClh
PC$RewVLoss_PC_R<- PC$Reward_meanPCrh - PC$Loss_meanPCrh
summary(PC$RewVLoss_PC_R)
df2<-merge(base, PC)
head(df2)
```

### Ventromedial prefrontal cortex
#### Left
```{r}
RewVMPFLh<- data_all %>%
  select(subjectkey, midrwposvsnegfkbetactxlhgp24,midrwposvsnegfkbetactxlhgp25, midrwposvsnegfkbetactxlhgp27, midrwposvsnegfkbetactxlhgp116, midrwposvsnegfkbetactxlhgp117, midrwposvsnegfkbetactxlhgp125) 

dim(RewVMPFLh)

RewVMPFLh$Rew_meanVMPFlh <- rowMeans(RewVMPFLh[,2:7], na.rm=TRUE)
colnames(RewVMPFLh)
```


```{r}
LossVMPFLh<- data_all %>%
  select(subjectkey, midlossposvsnegfkbctxlhgp24, midlossposvsnegfkbctxlhgp25, midlossposvsnegfkbctxlhgp27, midlossposvsnegfkbctxlhgp116, midlossposvsnegfkbctxlhgp117, midlossposvsnegfkbctxlhgp125)
dim(LossVMPFLh)

LossVMPFLh$Loss_meanVMPFlh <- rowMeans(LossVMPFLh[,2:7], na.rm=TRUE)
colnames(LossPCLh)
```
#### Right
```{r}
RewVMPFRh<- data_all %>%
  select(subjectkey, midrwposvsnegfkbetactxrhgp182,midrwposvsnegfkbetactxrhgp183, midrwposvsnegfkbetactxrhgp184, midrwposvsnegfkbetactxrhgp185, midrwposvsnegfkbetactxrhgp188, midrwposvsnegfkbetactxrhgp278, midrwposvsnegfkbetactxrhgp279) 

dim(RewVMPFRh)

RewVMPFRh$Rew_meanVMPFrh <- rowMeans(RewVMPFRh[,2:8], na.rm=TRUE)
colnames(RewVMPFRh)
```

```{r}
LossVMPFRh<- data_all %>%
  select(subjectkey, midlossposvsnegfkbctxrhgp182, midlossposvsnegfkbctxrhgp183, midlossposvsnegfkbctxrhgp184, midlossposvsnegfkbctxrhgp185, midlossposvsnegfkbctxrhgp188, midlossposvsnegfkbctxrhgp279,midlossposvsnegfkbctxrhgp278)
dim(LossVMPFRh)

LossVMPFRh$Loss_meanVMPFrh <- rowMeans(LossVMPFRh[,2:8], na.rm=TRUE)
colnames(LossPCRh)
```

```{r}
# head(LossVMPFLh)
LossVMPFLh_summary<-LossVMPFLh %>%
  select(subjectkey, Loss_meanVMPFlh)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))
head(LossVMPFLh_summary)
```


```{r}
# head(LossVMPFRh)
LossVMPFRh_summary<-LossVMPFRh %>%
  select(subjectkey, Loss_meanVMPFrh)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))
head(LossVMPFRh_summary)
```

```{r}
colnames(RewVMPFLh)
RewVMPFLh_summary<-RewVMPFLh %>%
  select(subjectkey, Rew_meanVMPFlh)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))
head(RewVMPFLh_summary)
```

```{r}
head(RewVMPFRh)
RewVMPFRh_summary<-RewVMPFRh %>%
  select(subjectkey, Rew_meanVMPFrh)%>% 
  group_by(subjectkey) %>% 
  summarise_all(funs(mean))
head(RewVMPFRh_summary)
```

```{r}
summary(LossVMPFLh$subjectkey)
VMPF_L<-merge(LossVMPFLh_summary, RewVMPFLh_summary)
dim(VMPF_L)
VMPF_R<-merge(LossVMPFRh_summary, RewVMPFRh_summary)
VMPF<-merge(VMPF_L, VMPF_R)
head(VMPF)

VMPF$RewVLoss_VMPF_L<- VMPF$Rew_meanVMPFlh - VMPF$Loss_meanVMPFlh
VMPF$RewVLoss_VMPF_R<- VMPF$Rew_meanVMPFrh - VMPF$Loss_meanVMPFrh
summary(VMPF$RewVLoss_VMPF_R)

df3<-merge(df2, VMPF)
head(df3)

RewVsLoss<-df3
```

```{r}
head(RewVsLoss)
head(subcort_RwLsAn)
```


```{r}
save(data_all, df,subcort_RwLsAn, RewVsLoss, file="~/Google Drive/ABCD/ABCD_puberty/_data/TOS2020/TOS2020_chp3_1.RData")
```

